version: "3"

services:
  
  app:

    container_name: app

    restart: always

    build: .
    env_file: 
        - .env
    environment:
        - NODE_ENV=production

        - PORT=5000

    ports:

      - "5000:5000"

    